### ISSUE TITLE
TUTORIAL TO BUILD AN APP

### ISSUE THREAD

**Issue by ninabreznik** [ESova/esova.github.io#3]
## What app will learners build?

**Idea:** Mobile app where kids can take a photo of i.e. broken window, hole in the street, abandoned car, some other local issue and the app automatically sends email to mayor's office.

More ideas?

**Comment by MatijaDjumic** [comment]
It would be good to have a few options. 
Some more ideas:

**Comment by MatijaDjumic** [comment]
1. An app that lists the info of all the busses and trains that commute within Šabac and from and to Šabac, with prices. With auto update schedules. 
2. Šabac city app - an app that lets users receive visitor event information and to search for restaurants, hotels, shopping, nightlife and parks, among other things. 
3. City news apps - an app that pulls all the current and relevant news about the region and updates the app.

**Comment by ninabreznik** [comment]
We will look into this. It might be too complicated to create such a sofisticated app & tutorial for complete beginners and solely online (without mentors) so have to think what is doable and will get back to you so we can see what would be the best option.

**Comment by ninabreznik** [comment]
@serapath I hope you can give some feedback here.

**Comment by serapath** [comment]
1. is totally easy or totally impossible, depending on whether the data is available via an open `API` or not
2. Here again - given the data is available, it's not too hard, but if it's not then it's very hard.
3. same

So I don't know what information is available and how easy it is to search for what's relevant, but if it should be better than a google search it all depends on where to get nicely curated data from. Do you have any ideas?

**Comment by MatijaDjumic** [comment]
1. Since the bus and train schedules are listed on official municipality websites, I'm sure we can get this info from them - since we're closely collaborating on this project.
2. I found this website (apparently not available in English lol): http://sabacturizam.org/ - this is the official website of the Šabac tourist organization - so Im suggesting to draw all the data from here. They have all the touristic, restaurant and other recommendations. 
   Then again, my question is - is it possible to just draw the data from this website like that? With the permission of the touristic organization ofcourse.
3. This is the official website of the Šabac TV - http://www.tvsabac.co.rs/vest.php The news data is available and Im almost 100% sure we can get the permission to draw the data from there. 

These are the sources we can draw the data from - however my noobish question is again, are these sources and the permission from the sources the only thing we need to solve the problem. :)

**Comment by serapath** [comment]
Regarding permissions, of course we would need those if they do not have `open API`s that everyone could just use, but I took that as a given.

Otherwise, in all scenarios, `1.`, `2.` and `3.` it basically boils down to:
**There is a huge difference between:**
- `train schedules` or `touristic information` or `tv news data` being listed or available on a website, which means basically you need to [`scrape`](https://en.wikipedia.org/wiki/Web_scraping) the website
- and having a nice [API](http://jsonapi.org/).

If they have a nice API, it's something that kids could do, if it needs to be scraped, the solution can be brittle (unstalbe) and the process can be highly complex and takes a lot more time and often will need complex debugging and cleaning of data (validation & sanitization) to get something useful that can be process by a program (e.g. a mobile app)

Regarding the skillset, usually people decide whether they want to specialize in building:
- web apps and/or mobile apps  (frontend engineer)
-  or build and connect API's (data engineer)

Most places on the internet these days do not have an `API` at all. Companies like `Twitter`, `Facebook` or `Google` have it or otherwise modern organizations.

You could official muncipality websites or sabacturizam or tvsabac and ask if any of them have their data available through APIs. There are currently several competing standards around implementing APIs, but they are all good, e.g.
- **http://jsonapi.org/** (youngest and maybe best one)
- http://swagger.io/
- http://raml.org/
- https://apiblueprint.org/

If they don't have an `API` already, the amount of work - and if kids should learn how to do it, the complexity involved in scraping - is huge and if using a data api should be part of the app, i'd recommend we try to come up with an idea that makes use of a service that has a free open API that follows existing standards.

**Comment by MatijaDjumic** [comment]
Alright perfect, got it. Thanks for the explanation! 
I will check the info regarding the APIs and get back to you.

**Comment by MatijaDjumic** [comment]
Ive presented the change of the end result of the app to Petar and he totally agrees - we should most definitely focus on the general knowledge and building the employability of the students.
