### ISSUE TITLE
[SPRINT 0]: PR & MARKETING

### ISSUE THREAD

**Issue by ninabreznik** [ESova/esova.github.io#6]
## Ideas:
- [ ] **Conference in Sabac - Future of Learning Programming**
- Topics: Coding in Schools, Changing a profession, Women in Tech
- Goal: connect with local influencers, create buzz, get publicity, find innovators (first triers)
- Speakers living in Berlin ( from Germany, New Zealand, France, Taiwan, Slovenia, Portugal etc.)
- Invite local geeky community to also prepare talks (or at least to help with hospitality and show guests/speakers around)
- Free workshops: What is Programming? How to get started?
- Some free sleep options for speakers (maybe even 1 or 2 kids from Wizard Amigos Institute)
- Somehow covered travel costs (bus/train/flight, van)

**Comment by MatijaDjumic** [comment]
Regarding the conference in Šabac some more details:
1. It will happen on the **4.9. - Friday** in Šabac.
2. All local IT influencers will be present
3. The goal is to present the eSova project to the local influencers and present them their role in the project itself. Answer all their questions as well. 
4. The event will be consisted of 3 separate parts - the WHY, the HOW and the WHAT. 
5. For this event, unfortunately, we dont have the budget defined for travel costs - those are the most recent news. In order to solve this problem we planned a part of the conference as a skype conference meeting between Šabac and Berlin.
6. I will define the whole event during this week and will send you the link to the spreadsheet so you can give your input simultaneously and see the details.

**Comment by ninabreznik** [comment]
Ok, keep us updated.

**Comment by MatijaDjumic** [comment]
Heres the spreadsheet that we will use for the event, the agenda is updated: https://docs.google.com/spreadsheets/d/1SsAkSKB2lU4CJ2-U1wD3ucSO8cncfIorYAh-hX8U_jg/edit#gid=0

Some key points of every session are written in the notes section. Feel free to give feedback and suggestions!

**Comment by serapath** [comment]
> (3.) The goal is to present the eSova project to the local influencers and present them their role in the project itself. Answer all their questions as well. 

For this we would need some more inspiration - to whom could you reach out - who would be in the audience, so we can think how to involve them and prepare for the **live skype session** accordingly

> (4.) The event will be consisted of 3 separate parts - the WHY, the HOW and the WHAT. 

The Details need to be worked out, but roughly speaking the story would go like:

#### WHY (Problem, now)

Statistics show:
- 50-80% of all current jobs are at risk of being automated in the coming decade
- programming is the new literacy people need to know to utilize this automation

#### WHAT (Goal, future)

Turning all kinds of people into programmers or at least give them enough understanding so that they can enhance their work skills with a bit of programming and to have in general a better understanding of programming and technology to be able to continue to learn and to be able to follow what's going on in this world and how technology is shaping our future

#### HOW (Solution, process)

It's possible to actually become a programmer and do something useful in 1-2 years of intensive practice. An online curriculum, where people go through a structured series of video tutorials and code examples, which explain them step by step how to build a basic app will get them there. Later they can modify and change this example app to something else and continue their process.

**Comment by serapath** [comment]
- I will collect all the links I have posted in the last couple of months and post them here, so we can get some backing regarding the **WHY**
- The Goal might need some more precision and I think it can be backed with some information about current technology trends, but maybe also job trends. I'd search some links and articles for that too and post them here to cover the **WHAT**
- The How is a lot about the specification of eSova and what we will do, where describing the user interface is something that can be done in more detail, while the actual APP that learners will build over the duration of many months is something that can be described but needs the most time and will take some weeks - the reasearch of what would make sense will take some time too and the inspiration of what will work best will come during that research and will make it more clear how the **HOW** will look like, but regarding that, I think the [WORKFLOW FOR PILOT Issue](https://waffle.io/ESova/Concept/cards/55cca51196165d11006c6d74) might be the right place to discuss that.

**Comment by MatijaDjumic** [comment]
Ill send you more info and a response to this tmrw.

**Comment by MatijaDjumic** [comment]
Alright, we got some valuable info regarding the IT influencers present at the event.
This is a list of all of them: https://docs.google.com/spreadsheets/d/1TOJXkz_OuOSOmWAzTur6LRGqrhl_TWhnbJt6SzXIByc/edit#gid=2144670799
- Im sorry for the spreadsheet being in Serbian again (it wasnt available in English). :(
  Heres a general conclusion:
- these are all high school and elementary school teachers
- some of them are not from the IT background (actually some of them teach the crafts class in parallel).
- Theres gonna be between 40 and 50 of them
- From the looks of it, and their background, they are not experts in the IT area

I propose a Skype meeting between the 4 of us (Petar, Nina, Alex and me) in order to cover the whole flow of the event and the sessions, so we can synchronize accordingly - a 30 min Skype.
If you're cool with this, maybe we can do it on Monday or Tuesday? What time would work the best for you?

**Comment by ninabreznik** [comment]
Hey, Matija, couldn't open the file... Need permission. But all in all, let's do Skype. Either tomorrow (mon) evening or Tuesday around 13h. Would that work for you, guys?

**Comment by MatijaDjumic** [comment]
Ive shared 2 files with you once again - same files just different links. Lets see if it works this way.
Tuesday 13h works perfectly - schedule it for that time. ;)

My skype name is: matija.djumic

**Comment by MatijaDjumic** [comment]
Just made a google cal. event, will update it with some discussion stuff - feel free to add anything you want. Nina can you please add Alex to the event? I dont have his email for some reason.

**Comment by ninabreznik** [comment]
Hey, unfortunately I didn't get a Google Cal invite... Please add us both with: ninabreznik@gmail.com and a.praetorius@serapath.de
Thanks :)

**Comment by MatijaDjumic** [comment]
Invited u guys to the event @ 10 PM ;)

**Comment by ninabreznik** [comment]
Hey, just to sum up for tomorrow:
- could you please **send us link to your slides** (Alex unfortunately doesn't have a pro account for Slides)
- we need to see how story goes so we can logically continue
- do you expect us to also show something (like some slides from our side?) - if so, **how can we display them for people (screen share?)**
- I suggest we go with **Hangout** again (not Skype), because we can do Screen sharing there if it is going to be necessary. Please, let us do the test call when you will have a break (**around 11:15?**) 
- Would you rather have **me translating what Alex will be saying** (because I know the content and can know what exactly he has in mind) **or** would it be better that **you** translate it for people (like after every 2-min of talking some short summary) - I would suggest we do so, if the internet connection wouldn't be good and we would break, otherwise I can try to do it
- you wrote our part should take 1,5h + Q&A. Do you think it is necessary to make it that long or would it be good to make it around **45min? and then see with Q&A** if people want to know more and then stretch it on how long they want
- is there anything else we need to know before tomorrow?

**Comment by MatijaDjumic** [comment]
1. Ive forwarded the email of my slides - this is the output with all of the content - the ppt will be shorter. 
2. I cant get Petars output until 9 PM - will be forwarded then by him.
3. It would be great if we got at least the basic slides - so the people can get an image. Not too much, because of possible lag.
4. Definitely agree - we can do the test call at 11 PM. We will test everything - sound, wifi connection, you translating, me translating and so on.
5. We can test both options and then see - Im cool with both.
6. YEs I agree - 1.5 h is definitely long - we can do 45 min and then QandA
7. Thats basically it - we will be in touch tomorrow - Ill connect to wifi as soon as I get there (7 AM) and will inform you if somethings up.

**Comment by ninabreznik** [comment]
Deal. We will do screensharing and have tabs open to show different tools and examples. And, honestly, i also think it will be best if you translate, because i haven't spoken serbian for quite some time and i think i will just studder if i will have to switch from english to serbian. I think it will be the smoothest if you there live paraphrase Alex's thoughts. But i will be there to help with Q&A and other things:)

We plan to be online around 10:30 and will then check all your messages and at 11:00 we wait for a test hangout call.

Break a leg/Drzimo palceve da event lepo uspe! Go go go!

**Comment by MatijaDjumic** [comment]
Alright, deal! See u @ 11 ;)

We will rock this!
